src/bothdefs.h, src/bothtools.c, src/common.c, src/pr2_vm.h, src/pr_comp.h, tools/qwdtools/source/init.c, tools/qwdtools/source/tools.c
This reverts commit b4a6d7a20e18f78babd6ac9fcb5efd1e615eec28.
This commit breaks KTX support and likely cause more problems as
pointed by @qqshka.
=> Revert "Fix PR1 on 64-bit, not checked against KTX"

src/pr2_cmds.c, src/server.h, src/sv_ccmds.c, src/sv_init.c, src/sv_save.c
Optional second parameter to "map" command, if not specified then server
defaults back to loading <mapname>.ent instead.
This lets users/mods support multiple .ent files for each map.
=> MAP: Allow user to specify entity file to load when changing map

meson.build
In an effort to get rid of cumbersome Makefiles or other custom configure things. Tested for native targets Linux, macOS and Windows/MSYS2. Cross compile tested from Linux -> Windows.
It actually tries to detect if you have libpcre installed and links to that library in case you have it. If not it will just compile the pcre files in the repository. Might be nice to not maintain those but rely on system installed libs. Keep in mind though that deployment then may require copying the libpcre library as well.
No ASM support for now. Mingw targets need to prevent `#define id386` in `quakeasm.h` unless someone knows how to compile these `.s` files nowadays.
Here is a linux -> mingw cross-compile example config for a 64 bit target (e.g. mingw.txt):
```
[binaries]
c = 'x86_64-w64-mingw32-gcc' …
```
=> add meson build file

meson.build
I actually missed that there is optional libcurl support for some www integration things.
=> MESON: add optional libcurl and www integration support

src/bothtools.c
Fix the check for VS version smaller than VS2015. This fixes a mingw build error.
The _WIN32 check is no needed as this is implied by _MSC_VER. And actually it should similar as it is done with vsnprintf below.
=> MINGW: proper checks for < VS2015

src/quakeasm.h
Since the ASM code is for x86 only, don't force it on Windows x86_64.
=> don't enable ASM on Windows x86_64

src/sv_demo.c, src/sv_move.c
This pull request removes a warning in clang:
warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
(in sv_move.c)
Also fixes a check for an empty string in sv_demo.c
Is this OK?
=> Fix compiler warnings on abs() and also fix empty d->name string check

src/net.h, src/net_chan.c, src/sv_main.c
- Feature: "qizmo" Packet Duplication by Spike
- Reasoning: minimize packet loss, improving connection from clients.
- Impacts: mvdsv (server to client - s2c - This pull request) and ezQuake (client to server - c2s - done:pullrequested)
**MVDSV implementation:**
`setinfo dupe 0-5 `
The new server cvar. A client sets a "dupe" value between 0 (no packet duplication, normal behavior) and 5 (5 packets duplicated). `setinfo dupe 1` sends one duplicated packet to the client. With higher dupe values, the default mvdsv rate limit of 50000 isn't enough for a busy fight - read nails  - (and rate cut happens). Hence the change to the hard-coded mvdsv rate limit of 100000, enabling server admins to set higher rate limit. From my tests, a value of 1 or 2 if fine for rate 50000 with lots of nails …
=> Enable s2c packet duplication

meson.build, meson_options.txt
Use `-Dforce_internal_pcre=true` when invoking meson.
E.g.
```
meson -Dforce_internal_pcre=true build
```
=> MESON: add option to force internal pcre files

meson.build, meson_options.txt, subprojects/pcre.wrap, tools/cross-compilation/linux-aarch64.txt
Wrap file installed by running the command:
```
meson wrap install pcre
```
Meson will automatically use the system copy of libpcre, if it can find it, and otherwise fall back to using the wrap, which is much more up to date than the vendored sources.
Users who prefer building a private, statically linked copy of pcre, even if a system copy is available, can do so by configuring meson with --wrap-mode=forcefallback.
Fixes #78
=> meson: drop the use of internal vendored pcre, in favor of wraps

.github/workflows/build-all-targets.yml
The whole idea of this pcre change was to have official builds
having pcre linked statically.
=> BUILD: On CI add meson option -Dwrap_mode=forcefallback

src/fs.c
PATHS: when getting a clean path check for ../ and ..\ instead of only .. as these are valid characters in player names and may be contained in demo filenames
=> PATHS: fix for demo names that contain multiple periods in a row

CMakeLists.txt
Unlocks optional longer compile times. cmake 3.9.0 was released Nov 30, 2018, so far from bleeding edge - CI is on 3.10.2.
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=1 ..
```
Previous output:
```
CMake Warning (dev) at CMakeLists.txt:103 (add_executable):
Policy CMP0069 is not set: INTERPROCEDURAL_OPTIMIZATION is enforced when
enabled.  Run "cmake --help-policy CMP0069" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
INTERPROCEDURAL_OPTIMIZATION property will be ignored for target 'mvdsv'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```
=> BUILD: Bump cmake limit to 3.9.0 to allow LTO.

src/server.h, src/sv_demo_misc.c, src/sv_main.c
**Usage**
```
laststats [<limit>]
<limit> = '0' for last 50 stats
<limit> = 'n' for last n stats (max 50)
<limit> = '' (empty) for last 10 stats
```
**Response**
results found
```
laststats <NUMBER_OF_RESULTS>
[
<STAT_ENTRY_JSON_BLOB>,
<STAT_ENTRY_JSON_BLOB>,
[...]
]
```
no results found:
```
laststats 0
[]
```
=> Add laststats (connectionless packet command) and revert lastscores.

src/cmodel.c, src/cmodel.h, src/vfs_pak.c, src/zone.c, src/zone.h
Read lump by lump instead of allocating memory covering the whole map in the temporary region, and sometimes adding an additional malloc that duplicates the data if lumps are not aligned.
This has become more relevant with mappers including lighting in BSPX lump and higher resolution textures, which isn't relevant to the server, but is still temporarily loaded into the heap before this PR.
=> BSP: Reduce memory during loadmap.

src/sv_demo_misc.c
=> Skip empty statistics files in laststats packetless command.

src/sv_user.c
Default value for sv_downloadchunksperframe is 15, you can set it up to 30. This shoud allow up to 1024 * 30 * 77 bytes per second download speed. Client should request such amount of chunks per frame though.
=> DOWNLOAD: bump download speed

src/sv_sys_unix.c, src/sv_sys_win.c, src/sys.h
…rflow on larger directories and never clean things up.  this is related to issue #135
=> BUG: use size_t for holding the size of a directory, continue calculating dir size after we've hit file number limit

src/pr2_exec.c
Duelers were alarmed by an apparent lack of randomness in starting spawns.
Some kind of seeding problem was suspected.
**phylter** and **Zorak** discovered the following:
`Sys_DoubleTime` returns approximate seconds since MVDSV launch.
RNG is seeded with `randomSeed = (int)(Sys_DoubleTime() * 100000)`.
Maximum value `randomSeed` can hold is 2147483647.
`(int)(Sys_DoubleTime() * 100000)` exceeds 2147483647 in just under 6 hours, after which the value stops increasing (or potentially behaves in an undefined way).
The code in question was introduced in 2021 (commit 837bdfcbd5bd061b6f34fec1737bfcfc3d7e58f2).
On affected servers, after 6 hours of uptime, it is possible to lock the starting spawns entirely by minimizing player activity (which can trigger RNG calls) during pre-war.
Seed the RNG …
=> replace rng seed generation

.github/workflows/build-and-deploy-release.yml, .github/workflows/build-and-deploy-snapshot.yml, .github/workflows/build-targets.yml
Also allows the `build-targets.yml` workflow to run in forks, like ktx and ezquake-source repositories work.
=> CI: Update build to work with newer docker.

.github/workflows/build-and-deploy-release.yml, .github/workflows/build-and-deploy-snapshot.yml, .github/workflows/build-targets.yml, src/g_public.h, src/pr2_cmds.c, src/pr_cmds.c, src/pr_edict.c, src/progs.h, src/sv_ents.c, src/sv_main.c, src/sv_user.c
FTE_PEXT_TRANS was broken when implemented long ago. This finishes the implementation, and also adds FTE_PEXT_COLOURMOD which was mostly declared in the protocol header, but not implemented. The latter is a convenient extension field for mappers to use when dealing with alpha brushes later on. For example using the same glass texture with alpha, but tint it via colormod field.
Broken clients (all ezQ versions) will be demoted to opaque entities based on revision.
When no entity has modified alpha or colormod, the additional bytes are not written. The PF_EXTRA_PFS will however still write one extra byte due to the moving of PF_ONGROUND and PF_SOLID. This is only a problem for buggy clients that have cl_pext_alpha set to 1, and somehow trick the server side check that would disable it if …
=> Support FTE_PEXT_TRANS and FTE_PEXT_COLOURMOD.

.gitignore, src/sv_main.c
Added three new serverinfo cvars:
- hostport
- countrycode
- city
Requested by Xantom:
```
mvdsv: currently hostname is used as a title, e.g. QUAKE.SE KTX:28501 and if there is an ongoing game QUAKE.SE KTX:28501 (red vs blue). This makes sense for the  in-game server browser.
But having to parse/guess info from that field is poo due to no common standard used. Another issue is trying to get proper geo info as ip lookup is pretty inaccurate.
Suggestions to config (optional)
• Add field *hostport (quake.se:28501)
• Add fields *cc (se), *city (Stockholm)
```
=> Add more serverinfo

CMakeLists.txt, src/bothdefs.h, src/bspfile.h, src/pr2_cmds.c, src/server.h, src/sv_demo.c, src/sv_ents.c
When merged, mvdsv must be paired with a new version of QTV or QTV-Go as previous versions didn't support these extensions.
=> PROTOCOL: Align MVD/QTV with gameplay protocol.

src/common.h, src/server.h, src/sv_demo_qtv.c, src/sv_main.c, src/sv_user.c
If a client has a userinfo key named qul set to 1, the server will relay QTV user list events to that client.
This feature allows ezQuake to display QTV users on the scoreboard.
=> Support sending QTV events to regular clients

CMakeLists.txt, src/common.c, src/qwsvdef.h, src/sv_broadcast.c, src/sv_broadcast.h, src/sv_ccmds.c, src/sv_main.c, src/sv_master.c, src/sv_sys_unix.c, src/sv_sys_win.c, src/sv_user.c, src/sys.h
By setting `sv_broadcast_enabled` to `1`, connected players can broadcast messages to other servers by typing:
`.qw <message>`
The server will emit the message to all servers retrieved from the configured master servers.
The payload that is sent is formatted as follows:
`\hostport\<hostport>\name\<name>\message\<message>`
When a server receives a message, the IP address and port of the sending server are prepended to the payload in the following format:
`\addr\<ip>:<port>`
If `\hostport` is set, that information is used in the message, otherwise, the sender's IP address and port are used as a fallback.
Example:
`[tot.qwsv.net:27500] ToT_Oddjob: prac please`
Messages are received using the new connectionless command broadcast, which serves as the endpoint for accepting messages from other …
=> Add message broadcasting

src/common.c, src/sv_broadcast.c, src/sv_broadcast.h, src/sv_sys_unix.c, src/sv_sys_win.c, src/sys.h
This PR addresses a few things that @jite pointed out:
1. Fixed the names of the mutex functions.
2. Added license headers to the new source files.
I also came up with a better way to emit broadcast messages that doesn't require using the main server socket. Instead, we now create a separate socket and include the actual server port in the broadcast payload.
As a result, we only need to validate the source address when determining whether a broadcast should be relayed.
This means that people who installed the version merged yesterday will not receive messages from servers using this fix, since the source port validation of the incoming message will fail.
I think this is acceptable, though, as no release has been made yet, and the previous PR was merged less than 24 hours ago.
=> Broadcast related fixes

src/pr2_cmds.c, src/sv_main.c, src/sv_user.c
1. Fix userinfo star usage in `PF2_SetBotUserInfo` the function incorrectly assumed that the provided userinfo key wasn't a star key.
2. If the client is a bot and has the `*skill` userinfo key set, display that value as the ping. Otherwise, fall back to the default bot ping of 10.
3. Add a new bitfield, `STATUS_SHOWCLIENTTYPE`, that outputs an extra column in the SVC_Status output: `h` for humans and `b` for bots. This could potentially be extended in the future to support other client types, such as service clients.
=> Three minor bot related fixes

src/common.c, src/common.h, src/sv_broadcast.c
This change adds the current number of players and the max clients value to the broadcast.
In the SVC broadcast function, we check whether this new data is available. If it is, a new format is used when relaying data to clients.
Old format:
`[tot.qwsv.net:27500] ToT_Oddjob: prac now`
New format:
`> tot.qwsv.net:27500 [6/8] ToT_Oddjob: prac now`
Special thanks to Xantom for coming up with the idea to include the player count, and to bps for helping reformat the output message
=> Update broadcast message
